# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assette}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tal Atlas"]
  s.date = %q{2011-03-06}
  s.description = %q{longer description of your gem}
  s.email = %q{me@tal.by}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/app/templates/foo/index.html.mustache",
    "examples/config.ru",
    "examples/defaults.rb",
    "examples/defaults.yml",
    "examples/public/images/test.pdf",
    "examples/public/javascripts/foo.js",
    "examples/public/javascripts/one.js",
    "examples/public/javascripts/test.coffee",
    "examples/public/javascripts/three.js",
    "examples/public/javascripts/two.js",
    "examples/public/stylesheets/one.css",
    "examples/public/stylesheets/one1.sass",
    "examples/public/stylesheets/two.css",
    "examples/public/stylesheets/two2.scss",
    "lib/assette.rb",
    "lib/assette/compiled_file.rb",
    "lib/assette/config.rb",
    "lib/assette/file.rb",
    "lib/assette/reader.rb",
    "lib/assette/readers.rb",
    "lib/assette/readers/coffee.rb",
    "lib/assette/readers/css.rb",
    "lib/assette/readers/js.rb",
    "lib/assette/readers/sass.rb",
    "lib/assette/readers/scss.rb",
    "lib/assette/server.rb",
    "lib/assette/template.rb",
    "lib/assette/template_set.rb",
    "spec/assette_spec.rb",
    "spec/file_spec.rb",
    "spec/reader_spec.rb",
    "spec/spec_helper.rb",
    "spec/template_spec.rb"
  ]
  s.homepage = %q{http://github.com/Talby/assette}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Asset manager thing}
  s.test_files = [
    "examples/defaults.rb",
    "spec/assette_spec.rb",
    "spec/file_spec.rb",
    "spec/reader_spec.rb",
    "spec/spec_helper.rb",
    "spec/template_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 1.16"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 1.16"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
  end
end

